name: 'Push Image'
description: 'This action pushes an image to Amazon ECR'
inputs:
  ECR_REGISTRY:
    required: true
    description: 'ECR registry'
  service:
    description: 'Service name'
    required: true
  image-tag:
    description: 'Image tag'
    required: true
    
runs:
  using: composite
  steps:
    - name: Push image to ECR
      id: push-image
      shell: bash
      run: |
        docker push ${{ inputs.image-tag }}
