name: "Build frontend"
description: "This action builds frontend"

runs:
  using: composite
  steps:
    - name: Build
      id: build-frontend
      shell: bash
      run: $GITHUB_ACTION_PATH/build.sh
