name: "Login ACR"
description: "Login to ACR"
inputs:
  aws-access-key-id:
    required: true
    description: "key-id"
  aws-secret-access-key:
    required: true
    description: "key-id"
  aws-region:
    required: true
    description: "key-id"

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 #v.6.1.0
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region}}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7 #v2.1.4
