name: 'Login ACR'
description: 'Login to ACR'
inputs:
  aws-access-key-id:
    required: true
    description: 'key-id'
  aws-secret-access-key:
    required: true
    description: 'key-id'
  aws-region:
    required: true
    description: 'key-id'

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region}}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
