name: "CodeArtifact - Get auth token & repository URL (PyPI)"
description: |
  Outputs an AWS CodeArtifact authorization token (“token”) and the
  corresponding PyPI repository URL (“repository_url”).

inputs:
  domain:
    description: CodeArtifact domain name
    required: true
  domain-owner:
    description: AWS account ID that owns the domain
    required: true
  region:
    description: AWS region where the domain lives (e.g. eu-central-1)
    required: true
  repository:
    description: Repository name that should appear in the PyPI URL path
    required: true

outputs:
  token:
    description: Short-lived auth token
    value: ${{ steps.get-token.outputs.token }}
  repository_url:
    description: Fully-qualified PyPI repository URL
    value: ${{ steps.get-token.outputs.repository_url }}
  index_url:
    description: Fully-qualified PyPI index URL
    value: "https://aws:${{ steps.get-token.outputs.token }}@${{ inputs.domain }}-${{ inputs.domain-owner }}.d.codeartifact.${{ inputs.region }}.amazonaws.com/pypi/${{ inputs.repository }}/simple/"

runs:
  using: "composite"
  steps:
    - name: Get CodeArtifact auth token & repository URL
      id: get-token
      shell: bash
      run: |
        set -euo pipefail

        # 1) Short-lived auth token
        TOKEN=$(aws codeartifact get-authorization-token \
          --domain        "${{ inputs.domain }}" \
          --domain-owner  "${{ inputs.domain-owner }}" \
          --region        "${{ inputs.region }}" \
          --query authorizationToken --output text)

        # 2) PyPI endpoint
        REPO=$(aws codeartifact get-repository-endpoint \
          --domain        "${{ inputs.domain }}" \
          --domain-owner  "${{ inputs.domain-owner }}" \
          --repository    "${{ inputs.repository }}" \
          --format pypi \
          --region        "${{ inputs.region }}" \
          --query repositoryEndpoint --output text)

        # 3) Expose outputs
        echo "token=$TOKEN" >> "$GITHUB_OUTPUT"
        echo "repository_url=$REPO" >> "$GITHUB_OUTPUT"
