name: 'lint and test'
description: 'This action will lint and test the code'
inputs:
  requirements:
    required: true
    description: 'requirements namefile'
  virtualenv:
    required: true
    description: 'virtualenv name'
  lint:
    description: 'lint condition'
  test:
    description: 'test condition'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    - name: Lint and Test
      shell: bash
      if: ${{ inputs.requirements && inputs.virtualenv }}
      run: |
        . /app/${{ inputs.virtualenv }}/bin/activate
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
        if ${{ inputs.lint }}; then make lint; fi
        if ${{ inputs.test }}; then make test; fi
