name: 'lint and test'
description: 'This action will lint and test the code'
inputs:
  requirements:
    description: 'requirements namefile'
  virtualenv:
    description: 'virtualenv name'
  lint:
    description: 'lint condition'
  test:
    description: 'test condition'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    - name: Enable virtualenv
      shell: bash
      if: ${{ inputs.virtualenv }}
      run: |
        . /app/${{ inputs.virtualenv }}/bin/activate
        pip -V
        pip install -r ${{ inputs.requirements }}
    - name: Install dependencies
      shell: bash
      if: ${{ inputs.requirements && !inputs.virtualenv }}
      run: |
        python -m pip install --upgrade pip
        pip -V
        pip install -r ${{ inputs.requirements }}
    - name: Lint with black and isort
      shell: bash
      if: ${{ inputs.lint }}
      run: |
        pwd
        ls
        make lint
    - name: Test with pytest
      shell: bash
      if: ${{ inputs.test }}
      run: |
        make test
