name: 'lint and test'
description: 'This action will lint and test the code'
inputs:
  requirements:
    description: 'requirements namefile'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f ${{ inputs.requirements }} ]; then pip install -r ${{ inputs.requirements }}; fi
    - name: Lint with black and isort
      shell: bash
      run: |
        make lint
    - name: Test with pytest
      shell: bash
      run: |
        make test
