name: "set image sha"
description: "This action sets the image sha into kustomization file"
inputs:
  image-name:
    required: true
    description: "image name"
  image-sha:
    required: true
    description: "image name"
  ecr-repository:
    required: true
    description: "repository name"
runs:
  using: composite
  steps:
    - name: Set image sha
      id: set-image-sha
      shell: bash
      run: |
        #curl -s -o /tmp/kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        #chmod u+x /tmp/kustomize
        cd $(eval echo $(echo $K8S_YAML_DIR | jq -r ".${GITHUB_REF#refs/heads/}"))
        kustomize edit set image ${{ inputs.image-name }}=${{ env.ECR_REGISTRY }}/${{ inputs.ecr-repository }}:${GITHUB_REF#refs/heads/}@sha256:${{ inputs.image-sha }}
