name: 'pull commit and push'
description: 'This action push the new changes'
runs:
  using: composite
  steps:
    - name: Push the changes to git
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add .
        git commit -m "Update image version" --allow-empty
        git push
