name: 'Build Image'
description: 'This action builds and tags an image'
inputs:
  ECR_REGISTRY:
    required: true
    description: 'ECR registry'
  service:
    description: 'Service to build'
    required: true
  location:
    description: 'Location of Dockerfile'
    required: true
  arguments:
    description: 'Build arguments'
    required: false
    
runs:
  using: composite
  steps:
    - name: Build and tag image
      id: build-image
      shell: bash
      run: |
        echo "${{ inputs.arguments }}"
        DOCKER_BUILDKIT=1 docker buildx build -f ${{ inputs.location }} . --cache-from ${{ inputs.ECR_REGISTRY }}/${{ inputs.service }}:${GITHUB_REF#refs/heads/} -t ${{ inputs.ECR_REGISTRY }}/${{ inputs.service }}:${GITHUB_REF#refs/heads/} ${{ inputs.arguments }} --build-arg BUILDKIT_INLINE_CACHE=1
        
        image_tag="${{ inputs.ECR_REGISTRY }}/${{ inputs.service }}:${GITHUB_REF#refs/heads/}"
        echo "Computed image_tag: $image_tag"
        echo "image-tag=$image_tag" >> $GITHUB_ENV
        echo "image-tag=$image_tag" >> $GITHUB_OUTPUT

outputs:
  image-tag:
    description: 'Image tag'
    value: ${{ steps.build-image.outputs.image-tag }}
