name: 'Scan Image'
description: 'This action scans an image'
inputs:
  service:
    description: 'Service name'
    required: true
  image-tag:
    description: 'Image tag'
    required: true
    
runs:
  using: composite
  steps:
    - name: Save Docker image to TAR file
      id: save-tar
      shell: bash
      run: |
        TAR_FILE="${{ inputs.service }}.tar"
        docker save -o ${TAR_FILE} ${{ inputs.image-tag }}
        echo "TAR_FILE=${TAR_FILE}" >> $GITHUB_ENV
        echo "Docker image saved as ${TAR_FILE}"
        
    - name: Inspector Scan
      id: inspector
      uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1.0.0
      with:
        artifact_type: 'container'
        artifact_path: ${{ env.TAR_FILE }}
        display_vulnerability_findings: "enabled"
        critical_threshold: 0

    - name: Check vulnerability threshold
      shell: bash
      run: |
        if [ ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }} -eq 1 ]; then
          echo "Vulnerability threshold exceeded. Failing the job."
          exit 1
        else
          echo "Vulnerability threshold not exceeded. Continuing."
        fi
