name: "Inspect Docker Image"
description: "Scans image with Amazon Inspector"

inputs:
  image:
    description: "Path to the image name that is going to be scanned"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: $AWS_REGION
        web-identity-token-file: $AWS_WEB_IDENTITY_TOKEN_FILE
        role-to-assume: $AWS_ROLE_ARN

    - name: Inspector Scan
      id: inspector
      uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1.0.0
      with:
        artifact_type: "container"
        artifact_path: ${{ inputs.image }} # Adjust the path here if needed
        display_vulnerability_findings: "enabled"
        critical_threshold: 0

    - name: Display CycloneDX SBOM (JSON)
      shell: bash
      run: cat ${{ steps.inspector.outputs.artifact_sbom }}

    - name: Display Inspector vulnerability scan results (JSON)
      shell: bash
      run: cat ${{ steps.inspector.outputs.inspector_scan_results }}

    - name: Display Inspector vulnerability scan results (Markdown)
      shell: bash
      run: cat ${{ steps.inspector.outputs.inspector_scan_results_markdown }}

    - name: On vulnerability threshold exceeded
      shell: bash
      run: |
        if [ ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }} -eq 1 ]; then
          echo "Vulnerability threshold exceeded. Failing the job."
          exit 1
        else
          echo "Vulnerability threshold not exceeded. Continuing."
        fi
