name: "Scan Image"
description: "This action scans an image"
inputs:
  scan_type:
    description: "Type of scan to perform (iac or image)"
    required: false
    default: "image"
  image:
    description: "Image to scan"
    required: true
  minimum_score:
    description: "Minimum score to pass the scan"
    required: false
  minimum_severity:
    description: "Minimum severity to fail the scan (low, medium, high, critical)"
    required: false
    default: "critical"
  minimum_exprt:
    description: "Minimum exploitability to fail the scan (low, medium, high, critical)"
    required: false
  exclude_vulnerabilities:
    description: "Comma-separated list of vulnerability IDs to exclude from the scan"
    required: false
  vuln_fixable_only:
    description: "Consider only fixable vulnerabilities"
    required: false
  minimum_detection_severity:
    description: "Minimum detection severity to fail the scan (low, medium, high, critical)"
    required: false
  show_full_description:
    description: "Show full vuln description in the report"
    default: "true"
  show_full_detection_details:
    description: "Show full detection details in the report"
    default: "true"
  timeout:
    description: "Timeout for the scan in seconds"
    required: false
    default: "300"
  falcon_client_id:
    description: "Falcon Client ID (passed as a secret)"
    required: true
  falcon_client_secret:
    description: "Falcon Client Secret (passed as a secret)"
    required: true
  output_path:
    description: "Path to save the scan results"
    required: false
    default: "./scan-results.json"

runs:
  using: composite
  steps:
    - name: Run FCS IaC Scan
      id: fcs-scan
      uses: crowdstrike/fcs-action@v2.0.2
      with:
        falcon_client_id: ${{ inputs.falcon_client_id }}
        falcon_region: "eu-1"
        scan_type: "${{ inputs.scan_type }}"
        image: "${{ inputs.image }}"
        minimum_score: "${{ inputs.minimum_score }}"
        minimum_severity: "${{ inputs.minimum_severity }}"
        minimum_exprt: "${{ inputs.minimum_exprt }}"
        exclude_vulnerabilities: "${{ inputs.exclude_vulnerabilities }}"
        vuln_fixable_only: "${{ inputs.vuln_fixable_only }}"
        minimum_detection_severity: "${{ inputs.minimum_detection_severity }}"
        show_full_description: "${{ inputs.show_full_description }}"
        show_full_detection_details: "${{ inputs.show_full_detection_details }}"
        timeout: "${{ inputs.timeout }}"
        output_path: "${{ inputs.output_path }}"
      env:
        FALCON_CLIENT_SECRET: ${{ inputs.falcon_client_secret }}

    - name: Check Scan Exit Code
      shell: bash
      run: |
        if [[ "${{ steps.fcs-scan.outputs.exit-code }}" != "0" ]]; then
          echo "::error::CrowdStrike scan failed with exit code: ${{ steps.fcs-scan.outputs.exit-code }}"
          exit 1
        fi

    - name: Generate Report Summary
      id: generate-report
      shell: bash
      run: |
        python ${{ github.action_path }}/generate-report.py ${{ inputs.output_path }}
