name: "Scan Image"
description: "This action scans an image"
inputs:
  scan_type:
    description: "Type of scan to perform (iac or image)"
    required: false
    default: "image"
  image:
    description: "Image to scan"
    required: true
  falcon_client_id:
    description: "Falcon Client ID (passed as a secret)"
    required: true
  falcon_client_secret:
    description: "Falcon Client Secret (passed as a secret)"
    required: true
  output_path:
    description: "Path to save the scan results"
    required: false
    default: "./scan-results.json"

runs:
  using: composite
  steps:
    - name: Run FCS IaC Scan
      id: fcs-scan
      uses: crowdstrike/fcs-action@v2.0.2
      with:
        falcon_client_id: ${{ inputs.falcon_client_id }}
        falcon_region: "eu-1"
        scan_type: "${{ inputs.scan_type }}"
        image: "${{ inputs.image }}"
        output_path: "${{ inputs.output_path }}"
      env:
        FALCON_CLIENT_SECRET: ${{ inputs.falcon_client_secret }}

    - name: Check Scan Exit Code
      shell: bash
      run: |
        if [[ "${{ steps.fcs-scan.outputs.exit-code }}" != "0" ]]; then
          echo "::error::CrowdStrike scan failed with exit code: ${{ steps.fcs-scan.outputs.exit-code }}"
          exit 1
        fi

    - name: Generate Report Summary
      id: generate-report
      shell: bash
      run: |
        python ${{ github.action_path }}/generate-report.py ${{ inputs.output_path }}
