name: "Scan Image"
description: "This action scans an image"
inputs:
  scan_type:
    description: "Type of scan to perform (iac or image)"
    required: false
    default: "image"
  image:
    description: "Image to scan"
    required: true
  falcon_client_id:
    description: "Falcon Client ID (passed as a secret)"
    required: true
  falcon_client_secret:
    description: "Falcon Client Secret (passed as a secret)"
    required: true
  output_path:
    description: "Path to save the scan results"
    required: false
    default: "./upload-results/"
  report_formats:
    description: "Report formats to generate (comma-separated)"
    required: false
    default: "json"

runs:
  using: composite
  steps:
    - name: Run FCS IaC Scan
      uses: crowdstrike/fcs-action@v2.0.2
      with:
        falcon_client_id: ${{ inputs.FALCON_CLIENT_ID }}
        falcon_region: "eu-1"
        scan_type: "${{ inputs.scan_type }}"
        image: "${{ inputs.image }}"
        output_path: "${{ inputs.output_path }}"
        report_formats: "${{ inputs.report_formats }}"
      env:
        FALCON_CLIENT_SECRET: ${{ inputs.FALCON_CLIENT_SECRET }}
