name: "Create docker manifest"
description: "Merge multi arch docker images into a single manifest"
inputs:
  registry:
    description: "Registry URL"
    required: true
  image:
    description: "Image name"
    required: true
  tag:
    description: "Final tag to be used for the manifest"
    required: true
  tag-suffixes:
    description: "List of tag suffixes used for the manifest (e.g. amd64 or arm64)"
    required: true

runs:
  using: composite
  steps:
    - name: Debug Inputs
      shell: bash
      run: |
        echo "Registry: ${{ inputs.registry }}"
        echo "Image: ${{ inputs.image }}"
        echo "Tag: ${{ inputs.tag }}" 
        echo "Tag Suffixes: ${{ inputs.tag-suffixes }}"

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Create and push manifest
      shell: bash
      run: |
        #! /bin/bash
        # Enable docker manifest command
        export DOCKER_CLI_EXPERIMENTAL=enabled
        
        IFS=',' read -ra suffixes <<< "${{ inputs.tag-suffixes }}"

        # Build manifest create command
        manifest_cmd="docker buildx imagetools create -t ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}"

        # Add each architecture to the manifest command
        for ((i=0; i<${#suffixes[@]}; i++)); do
            suffix="${suffixes[$i]}"
            manifest_cmd+=" ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}-${suffix}"
        done
      
        echo "Running manifest command: $manifest_cmd"
        $manifest_cmd