name: 'get docker image sha'
description: 'This action retrives the docker image sha'
inputs:
  aws-id:
    required: true
    description: 'aws id'
  ecr-repository:
    required: true
    description: 'repository name'
  image-tag:
    required: true
    description: 'image tag name'
outputs:
  image-sha:
    description: 'output of the docker image sha'
    value: ${{ steps.get-docker-image-sha.outputs.image-sha }}
runs:
  using: composite
  steps:
    - name: Get docker image sha
      id: get-docker-image-sha
      shell: bash
      run: echo "image-sha=$(aws ecr describe-images --registry-id ${{ inputs.aws-id }} --repository-name ${{ inputs.ecr-repository }} --image-ids imageTag=${{ inputs.image-tag }} | jq '.imageDetails[0].imageDigest' | sed 's/.*://' | tr -d '"')" >> $GITHUB_OUTPUT
