name: "Tag image"
description: "This action tag image"
inputs:
  image-tag:
    required: true
    description: "image tag"
  ECR_REGISTRY:
    description: "ECR registry id"
    required: true
  ECR_REPOSITORY:
    description: "ECR repository name"
    required: true

runs:
  using: composite
  steps:
    - name: Tag image
      id: tag-image
      shell: bash
      run: |
        docker tag ${{ inputs.image-tag }} ${{env.ECR_REGISTRY}}/${{ inputs.ECR_REPOSITORY }}:${GITHUB_REF#refs/heads/}
        image_tag="${{env.ECR_REGISTRY}}/${{ inputs.ECR_REPOSITORY }}:${GITHUB_REF#refs/heads/}"
        echo "image-tag=$image_tag" >> $GITHUB_OUTPUT
outputs:
  image-tag:
    description: "image tag"
    value: ${{ steps.tag-image.outputs.image-tag }}
