name: "Docker build"
description: "This action build the image"
inputs:
  dockerfile:
    required: true
    description: "DockerFile"
  dockerArgs:
    required: false
    description: "Build args"
  image:
    description: "Image"
    required: true
  context:
    description: "Build context"
    required: false
    default: "."
outputs:
  image:
    description: "Output of build image"
    value: ${{ inputs.image }}
runs:
  using: composite
  steps:
    - name: Build
      id: build-image
      shell: bash
      run: |
        docker build -f ${{ inputs.dockerfile }} ${{ inputs.dockerArgs }} --cache-from ${{ inputs.image }} -t ${{ inputs.image }} ${{ inputs.context }}
