name: 'build tag and push image'
description: 'This action build tag and push image'
inputs:
  ECR_REGISTRY:
    required: true
    description: 'ECR registry'
  TAG:
    required: true
    description: 'last_successful_commi_tag'
  SHA:
    required: true
    description: 'current tag'
  service:
    description: 'service to build'
    required: true
  location:
    description: 'location of dockerfile'
    required: true
  arguments:
    description: 'build arguments'
    required: false
runs:
  using: composite
  steps:
    - name: Build, tag, and push image to Amazon ECR
      id: build-image-sha
      shell: bash
      run: |
        docker build -f ${{ inputs.location }} . --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${{env.ECR_REGISTRY}}/${{ inputs.service }}:${GITHUB_REF#refs/heads/} -t ${{env.ECR_REGISTRY}}/${{ inputs.service }}:${GITHUB_REF#refs/heads/} ${{ inputs.arguments }}
        docker push ${{env.ECR_REGISTRY}}/${{ inputs.service }}:${GITHUB_REF#refs/heads/}
    - name: Remove untagged docker images
      id: remove-untagged-images
      shell: bash
      run: docker image prune -af
