name: "Login ECR"
description: "Login to ECR"
inputs:
  aws-region:
    required: true
    description: "AWS region"
  aws-id:
    required: true
    description: "AWS id"

runs:
  using: composite
  steps:
    - name: Login to Amazon ECR
      shell: bash
      id: ecr-login
      env:
        REGISTRY: ${{ inputs.aws-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
      run: |
        docker login --username AWS -p $(aws ecr get-login-password --region ${{ inputs.aws-region }}) $REGISTRY
        echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
