name: 'Login ECR'
description: 'Login to ECR'
inputs:
  aws-region:
    required: true
    description: 'key-id'

runs:
  using: composite
  steps:
    - name: Login to Amazon ECR
      id: ecr-login
      run: docker login --username AWS -p $(aws ecr get-login-password --region ${{ env.aws_region }}) ${{ env.docker_registry_id }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com
