# .github/actions/codeartifact-auth/action.yml
name: "CodeArtifact ‑ Get auth token & registry URL"
description: |
  Outputs an AWS CodeArtifact authorization token (“token”) and the
  corresponding npm registry URL (“registry”).

inputs:
  domain:
    description: CodeArtifact domain name
    required: true
  domain-owner:
    description: AWS account ID that owns the domain
    required: true
  region:
    description: AWS region where the domain lives (e.g. eu-central-1)
    required: true
  repository:
    description: Repository name that should appear in the npm URL path
    required: true

outputs:
  token:
    description: Short‑lived authorization token for login
  registry:
    description: Fully‑qualified  registry URL for the repository

runs:
  using: "composite"
  steps:

    - name: Get CodeArtifact auth token and registry URL
      id: get-token
      shell: bash
      run: |
        set -eo pipefail

        TOKEN=$(aws codeartifact get-authorization-token \
          --domain "${{ inputs.domain }}" \
          --domain-owner "${{ inputs.domain-owner }}" \
          --region "${{ inputs.region }}" \
          --query authorizationToken --output text)

        echo "token=$TOKEN" >> "$GITHUB_OUTPUT"
        echo "registry=https://${{ inputs.domain-owner }}.d.codeartifact.${{ inputs.region }}.amazonaws.com/npm/${{ inputs.repository }}/" >> "$GITHUB_OUTPUT"
