name: "lint and test"
description: "This action will lint and test the code"
inputs:
  requirements:
    required: true
    description: "requirements namefile"
  virtualenv:
    required: true
    description: "virtualenv name"
  python-version:
    required: true
    description: Python Version to run
  pip-version:
    required: true
    description: Python Pip Version to install
  lint:
    description: "lint condition"
  test:
    description: "test condition"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Lint and Test
      shell: bash
      if: ${{ inputs.requirements && inputs.virtualenv }}
      run: |
        . /app/${{ inputs.virtualenv }}/bin/activate
        python -m pip install --upgrade "pip<${{ inputs.pip-version }}"
        pip install -r ${{ inputs.requirements }}
        if [ "${{ inputs.lint }}" ]; then make lint; fi
        if [ "${{ inputs.test }}" ]; then make test; fi
