name: 'Save Docker Image to TAR'
description: 'Saves a Docker image to a TAR file'

inputs:
  image:
    description: 'Docker image to save'
    required: true
  tar_file:
    description: 'Path to save the TAR file'
    required: true

runs:
  using: composite
  steps:
    - name: Save Docker image to TAR file
      shell: bash
      run: |
        TAR_FILE="${{ inputs.tar_file }}"
        docker save -o ${TAR_FILE} ${{ inputs.image }}
        echo "TAR_FILE=${TAR_FILE}" >> $GITHUB_ENV
        echo "Docker image saved as ${TAR_FILE}"
        ls -la ${TAR_FILE}
