name: 'Save Docker Image to TAR'
description: 'Saves a Docker image to a TAR file'

inputs:
  image:
    description: 'Docker image to save'
    required: true
  tar_file:
    description: 'Path to save the TAR file'
    required: true

runs:
  using: composite
  steps:
      - name: Save Docker image to TAR file
        shell: bash
        run: |
          IFS=':' read -r IMAGE TAG <<< "${{ inputs.image }}"
          echo "Saving image ${IMAGE}:${TAG} to TAR file..."
          TAR_FILE="${IMAGE}-${TAG}.tar"
          docker save -o ${TAR_FILE} 686474074286.dkr.ecr.eu-central-1.amazonaws.com/${IMAGE}:${TAG}
          echo "TAR_FILE=${TAR_FILE}" >> $GITHUB_ENV
          echo "Docker image saved as ${TAR_FILE}"
          ls -la
          pwd

      - name: Sanitize artifact name
        id: sanitize-artifact-name
        shell: bash
        run: |
          SANITIZED_NAME=$(echo "${{ inputs.image }}-tar" | sed 's/[:\/]/-/g')
          echo "SANITIZED_NAME=${SANITIZED_NAME}" >> $GITHUB_ENV

      - name: Upload TAR file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SANITIZED_NAME }}
          path: ${{ env.TAR_FILE }}
