name: Crowdstrike scan test
on:
  workflow_dispatch:
env:
  EU_AWS_ID: 861208160487
  EU_AWS_REGION: eu-central-1
jobs:
  build:
    name: Scan Image
    runs-on: ${{ vars.EU_GITHUB_RUNNER }}-amd64
    steps:
      - name: Checkout data-surveillance
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          repository: CardoAI/data-surveillance
          token: ${{ secrets.GH_PAT }}

      - name: EU ECR login
        uses: CardoAI/composite/ecrlogin_with_role@main
        with:
          aws-region: ${{ env.EU_AWS_REGION }}
          aws-id: ${{ env.EU_AWS_ID }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #v4.0.0

      - name: Docker Build
        run: docker buildx build --load -t backend-main-amd64 -f deployment/Dockerfile .

      - name: Docker Images
        run: docker image ls

      - name: Scan Image
        uses: CardoAI/composite/scan_image_v5@main
        id: scan-image
        with:
          image: backend-main-amd64
          falcon-client-id: ${{ secrets.FALCON_CLIENT_ID }}
          falcon-client-secret: ${{ secrets.FALCON_CLIENT_SECRET }}
